create table tenants (
    tenant_id varchar(64) primary key,
    name varchar(120) not null,
    status varchar(32) not null,
    plan_code varchar(32) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table workspaces (
    workspace_id varchar(64) primary key,
    tenant_id varchar(64) not null,
    name varchar(120) not null,
    status varchar(32) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint fk_workspaces_tenant foreign key (tenant_id) references tenants (tenant_id)
);

create index idx_workspace_tenant on workspaces (tenant_id);

create table users (
    user_id varchar(64) primary key,
    email varchar(255) not null unique,
    display_name varchar(120) not null,
    status varchar(32) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table workspace_memberships (
    id bigint generated by default as identity primary key,
    tenant_id varchar(64) not null,
    workspace_id varchar(64) not null,
    user_id varchar(64) not null,
    role varchar(32) not null,
    status varchar(32) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint fk_memberships_tenant foreign key (tenant_id) references tenants (tenant_id),
    constraint fk_memberships_workspace foreign key (workspace_id) references workspaces (workspace_id),
    constraint fk_memberships_user foreign key (user_id) references users (user_id),
    constraint uk_membership_workspace_user unique (workspace_id, user_id)
);

create index idx_membership_workspace_user on workspace_memberships (workspace_id, user_id);

create table channels (
    channel_id varchar(64) primary key,
    tenant_id varchar(64) not null,
    workspace_id varchar(64) not null,
    name varchar(120) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint fk_channels_tenant foreign key (tenant_id) references tenants (tenant_id),
    constraint fk_channels_workspace foreign key (workspace_id) references workspaces (workspace_id)
);

create index idx_channel_workspace on channels (workspace_id);

create table messages (
    message_id varchar(64) primary key,
    tenant_id varchar(64) not null,
    workspace_id varchar(64) not null,
    channel_id varchar(64) not null,
    author_user_id varchar(64) not null,
    body varchar(4000) not null,
    parent_message_id varchar(64),
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint fk_messages_tenant foreign key (tenant_id) references tenants (tenant_id),
    constraint fk_messages_workspace foreign key (workspace_id) references workspaces (workspace_id),
    constraint fk_messages_channel foreign key (channel_id) references channels (channel_id),
    constraint fk_messages_author foreign key (author_user_id) references users (user_id),
    constraint fk_messages_parent foreign key (parent_message_id) references messages (message_id)
);

create index idx_message_channel on messages (channel_id, created_at);

create table documents (
    document_id varchar(64) primary key,
    tenant_id varchar(64) not null,
    workspace_id varchar(64) not null,
    title varchar(200) not null,
    content varchar(12000) not null,
    status varchar(32) not null,
    created_by_user_id varchar(64) not null,
    last_modified_by_user_id varchar(64) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint fk_documents_tenant foreign key (tenant_id) references tenants (tenant_id),
    constraint fk_documents_workspace foreign key (workspace_id) references workspaces (workspace_id),
    constraint fk_documents_creator foreign key (created_by_user_id) references users (user_id),
    constraint fk_documents_modifier foreign key (last_modified_by_user_id) references users (user_id)
);

create index idx_documents_workspace on documents (workspace_id);

create table document_comments (
    comment_id varchar(64) primary key,
    document_id varchar(64) not null,
    author_user_id varchar(64) not null,
    body varchar(4000) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint fk_document_comments_document foreign key (document_id) references documents (document_id),
    constraint fk_document_comments_author foreign key (author_user_id) references users (user_id)
);

create index idx_document_comments_document on document_comments (document_id, created_at);
