spring:
  docker:
    compose:
      enabled: false
  datasource:
    url: jdbc:h2:file:./data/platform-local;MODE=PostgreSQL;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
